kind: pipeline
name: default

steps:
  - name: integration test
    image: node:12.4.0
    commands:
      - npm ci
      - npm run test
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      STAGE: dev
      REGION: us-east-1
    when:
      event:
        - push

  - name: build
    image: node:12.4.0
    commands:
      - node build.js "misu"
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      STAGE: dev
      REGION: us-east-1
    when:
      event:
        - push

  - name: deploy
    image: hashicorp/terraform:0.11.12
    commands:
      - MD5=$(cat workshop_md5.txt)
      - cd terraform
      - terraform init
      - terraform apply --var "my_name=misu" --var "file_name=$MD5" -auto-approve
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      STAGE: dev
      REGION: us-east-1
    when:
      event:
        - push

  - name: acceptance test
    image: node:12.4.0
    commands:
      - npm run acceptance
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      STAGE: dev
      REGION: us-east-1
    when:
      event:
        - push